project:
  type: website

website:
  title: "Mitesh Kumar"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Education & Achievements

format:
  html:
    theme: darkly
    css: styles.css
    page-layout: custom
    toc: false
