project:
  type: website
  resources:
    - custom.js
    - styles.css
    - ".nojekyll"

website:
  title: "Mitesh Kumar"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Education & Achievements
    right:
      - icon: github
        href: "https://github.com/miteshkumar07"
      - icon: linkedin
        href: "https://www.linkedin.com/in/mitesh-kumar0707/"

format:
  html:
    theme: darkly
    css: styles.css
    page-layout: custom
    toc: false
    include-in-header: analytics.html
